### PR TITLE
Allow update from *.ubuntu.com on  TCP/80

### PR DESCRIPTION
**Pull request by SileyeDevOps**
## Description

_Describe the changes needed_

### CODE REVIEW

**Comment by SileyeDevOps** [comment]
Add *.ubuntu.com to the filter.

sudo apt-get update -y
sudo apt-get upgrade -y

**Review by Sileye79 — COMMENTED** [review]
Everything looks good. Approve by SecOps

**Comment by Sileye79** [comment]
Approve by SecOps

**Review by Sileye79 — COMMENTED** [review]
Approve by SecOps

**Review by Sileye79 — COMMENTED** [review]
It looks fine

**Review by Sileye79 — COMMENTED** [review]
Nice I love it

**Comment by SileyeDevOps** [comment]
Reopen and approve

**Comment by Sileye79** [comment]
Approve

**Pull request closed without merging**
